api_version = "2024-10"

[[extensions]]
type = "ui_extension"
name = "thank-you-sns-share"
handle = "thank-you-sns-share"

[[extensions.targeting]]
target = "purchase.thank-you.block.render"
module = "./src/ThankYouExtension.tsx"

[extensions.capabilities]
api_access = true
network_access = true
block_progress = false
